import { PubAnyCover } from '@/types/pub-cover.type';

export const pubCovers: PubAnyCover[] = [
  {
    id: 'food-society',
    src: 'https://ganache.studio/videos/pubs/food_society/video.mp4',
    vimeoUrl: 'https://player.vimeo.com/video/809031020?h=1e6e37278d&title=0&byline=0&portrait=0',
    poster: 'https://ganache.studio/videos/pubs/food_society/poster.jpg',
    title: 'FOOD SOCIETY',
    producer: 'Théo Vincent',
    type: 'Film de marque',
    agence: 'Fullmoun',
    format: 'horizontal',
  },
  {
    id: 'vowels',
    src: 'https://ganache.studio/videos/pubs/vowels/video.mp4',
    vimeoUrl: 'https://player.vimeo.com/video/1057439487?title=0&byline=0&portrait=0',
    poster: 'https://ganache.studio/videos/pubs/vowels/poster.jpg',
    title: 'VOWELS',
    producer: 'Andreas Pappamikail',
    type: 'Film de marque',
    format: 'horizontal',
  },
  {
    id: 'heineken',
    src: 'https://ganache.studio/videos/pubs/heineken/video.mp4',
    vimeoUrl: 'https://player.vimeo.com/video/707739875?h=bbdbbf164f&title=0&byline=0&portrait=0',
    poster: 'https://ganache.studio/videos/pubs/heineken/poster.jpg',
    title: 'HEINEKEN',
    producer: 'Aurélien Grellier-Beker',
    type: 'Campagne social media',
    agence: 'Publicis Conseil',
    format: 'horizontal',
  },
  {
    id: 'florajet',
    src: 'https://ganache.studio/videos/pubs/florajet/video.mp4',
    vimeoUrl: 'https://player.vimeo.com/video/833260644?h=59fc5138f5&title=0&byline=0&portrait=0',
    poster: 'https://ganache.studio/videos/pubs/florajet/poster.jpg',
    title: 'FLORAJET',
    producer: 'Rémy Cayuela',
    type: 'Film TV',
    agence: 'Le Nouveau Bélier',
    format: 'horizontal',
  },
  {
    id: 'lgn',
    src: 'https://ganache.studio/videos/pubs/lgn/video.mp4',
    vimeoUrl: 'https://player.vimeo.com/video/970564462?title=0&byline=0&portrait=0',
    poster: 'https://ganache.studio/videos/pubs/lgn/poster.jpg',
    title: 'LGN LOUIS GABRIEL NOUCHI',
    producer: 'Andreas Pappamikail',
    type: 'Campagne social media',
    format: 'horizontal',
  },
  {
    id: 'prince-de-bretagne',
    src: 'https://ganache.studio/videos/pubs/prince_de_bretagne/video.mp4',
    vimeoUrl: 'https://player.vimeo.com/video/717927697?h=1262268991&title=0&byline=0&portrait=0',
    poster: 'https://ganache.studio/videos/pubs/prince_de_bretagne/poster.jpg',
    title: 'PRINCE DE BRETAGNE',
    producer: 'Julien Thiverny',
    type: 'Film TV',
    agence: 'Josiane',
    format: 'horizontal',
  },
  {
    id: 'saint-gobain',
    src: 'https://ganache.studio/videos/pubs/saint_gobain/video.mp4',
    vimeoUrl: 'https://player.vimeo.com/video/737931861?h=ae743b9c61&title=0&byline=0&portrait=0',
    poster: 'https://ganache.studio/videos/pubs/saint_gobain/poster.jpg',
    title: 'SAINT GOBAIN',
    producer: 'Théo Vincent',
    type: 'Film TV',
    agence: 'Josiane',
    format: 'horizontal',
  },
  {
    id: 'maison-margiela',
    src: 'https://ganache.studio/videos/pubs/maison_margiela/video.mp4',
    vimeoUrl: 'https://player.vimeo.com/video/576917131?h=f4e9b7c41b&title=0&byline=0&portrait=0',
    poster: 'https://ganache.studio/videos/pubs/maison_margiela/poster.jpg',
    title: 'MAISON MARGIELA',
    producer: 'Aurélien Grellier-Beker',
    type: 'Campagne social media',
    format: 'horizontal',
  },
  {
    id: 'ornikar',
    src: 'https://ganache.studio/videos/pubs/ornikar/video.mp4',
    vimeoUrl: 'https://player.vimeo.com/video/835818764?h=d36a9a470e&title=0&byline=0&portrait=0',
    poster: 'https://ganache.studio/videos/pubs/ornikar/poster.jpg',
    title: 'ORNIKAR',
    producer: 'Julien Thiverny',
    type: 'Campagne social media',
    agence: 'Josiane',
    format: 'horizontal',
  },
  {
    id: 'lgn-2',
    src: 'https://ganache.studio/videos/pubs/lgn_2/video.mp4',
    vimeoUrl: 'https://player.vimeo.com/video/884433759?h=4cfe06afed&title=0',
    poster: 'https://ganache.studio/videos/pubs/lgn_2/poster.jpg',
    title: 'LGN LOUIS GABRIEL NOUCHI',
    producer: 'Andreas Pappamikail',
    type: 'Campagne social media',
    format: 'vertical',
  },
  {
    id: 'racine-avocats',
    src: 'https://ganache.studio/videos/pubs/racine_avocats/video.mp4',
    vimeoUrl: 'https://player.vimeo.com/video/746829188?h=4a709ee1ff&title=0&byline=0&portrait=0',
    poster: 'https://ganache.studio/videos/pubs/racine_avocats/poster.jpg',
    title: 'RACINE AVOCATS',
    producer: 'Aurélien Grellier-Beker',
    type: 'Film Corporate',
    format: 'square',
  },
];
